close all
clear all
load ../Data/confmat_comb.mat
Rp = 5*60; %CFH/person for office building for people outdoor air rate
Ra = 0.06*60; %CFH/ft2 for area outdoor air rate
area = 10*14; %ft2, size 8*10*14
thres = 1;
adjust_occ_log = 0;
adjust_occ_mlp = 0;
adjust_occ_bn = 0;
adjust_occ_log2 = 2;
adjust_occ_mlp2 = 2;
adjust_occ_bn2 = 2;
other_occ_vec = [0,7,5,3,4,2,1,6];
method = 'light'; % or 'heavy'
schedule_mat = light_mat; % or heavy_mat
name1 = ['Hour_Schedule_' method];
name2 = ['Daily_Ventillation_Comparison_' method];
name3 = ['Daily_Violation_Comparison_' method];
methods_list = repmat({'Conservative','Fixed','BayesNet','MLP','Logistic','SbP'},1,2);
simobs = [repmat({'Sim.A'},1,6),repmat({',B'},1,6)];
%% simulation


[occ_mat,safe_strategy,fixed_strategy,...
    sbp_strategy,bn_strategy,mlp_strategy,...
    log_strategy,safe_vio,fixed_vio,sbp_vio,...
    bn_vio,mlp_vio,log_vio] = simulate_methods_energy...
    (schedule_mat,Ra,Rp,area,thres,adjust_occ_log,...
    adjust_occ_mlp,adjust_occ_bn,other_occ_vec);
[occ_mat,safe_strategy2,fixed_strategy2,...
    sbp_strategy2,bn_strategy2,mlp_strategy2,...
    log_strategy2,safe_vio2,fixed_vio2,sbp_vio2,...
    bn_vio2,mlp_vio2,log_vio2] = simulate_methods_energy...
    (schedule_mat,Ra,Rp,area,thres,adjust_occ_log2,...
    adjust_occ_mlp2,adjust_occ_bn2,other_occ_vec);

figure_t = figure;
boxplot(occ_mat,'plotstyle','compact','boxstyle','filled',...
    'medianstyle','target','symbol','',...
    'notch','on','colors',[50,205,50]/255,...
    'labelverbosity','minor','whisker',0.5,...
    'widths',0.6,'labelorientation','horizontal',...
    'labels',{'1','','','','','6','',...
    '','','','','12','','','','',...
    '','18','','','','','','24'})
xlabel('Hour of the day','FontName','Times New Roman','FontSize',13.5);
ylabel('Number of occupants','FontName','Times New Roman','FontSize',13.5);
set(figure_t, 'Position', [100, 100, 550, 200]);


vent_mat1 = [safe_strategy',fixed_strategy',bn_strategy',...
     mlp_strategy',log_strategy',sbp_strategy'];
vent_mat2 = [safe_strategy2',fixed_strategy2',bn_strategy2',...
     mlp_strategy2',log_strategy2',sbp_strategy2'];
vent_mat = [vent_mat1,vent_mat2]/(10000);
figure_t = figure;
boxplot(vent_mat,{methods_list,simobs},'colors',...
    repmat('cm',1,6),'factorgap',[18 0],'labelverbosity',...
    'minor','plotstyle','compact','boxstyle','outline',...
    'medianstyle','target','symbol','r+',...
    'notch','on',...
    'whisker',1.5,...
    'widths',0.6,'labelorientation','horizontal')
%xlabel('Methods','FontName','Times New Roman','FontSize',13.5);
ylabel('Ventillation (1e4 cubic feet)','FontName','Times New Roman','FontSize',13.5);
ylim([1,6]);
set(figure_t, 'Position', [100, 100, 550, 220]);
hLegend = legend(findall(gca,'Tag','Box'), {'Exp. w. adjustment','Exp. w/o adjustment'},'Orientation','horizontal','Location','NorthWest');


vio_plot1 = [sum(safe_vio,2),sum(fixed_vio,2),...
    sum(bn_vio,2),sum(mlp_vio,2),...
    sum(log_vio,2),sum(sbp_vio,2)];
vio_plot2 = [sum(safe_vio2,2),sum(fixed_vio2,2),...
    sum(bn_vio2,2),sum(mlp_vio2,2),...
    sum(log_vio2,2),sum(sbp_vio2,2)];
vio_plot = [vio_plot1,vio_plot2];
figure_t = figure;
boxplot(vio_plot,{methods_list,simobs},'colors',...
    repmat('cm',1,6),'plotstyle','compact','boxstyle','outline',...
    'medianstyle','target','symbol','r+',...
    'notch','on',...
    'labelverbosity','minor','whisker',1.5,...
    'widths',0.6,'labelorientation','horizontal',...
    'factorgap',[18 0])
ylim([0,8]);
ylabel('Daily violations','FontName','Times New Roman','FontSize',13.5);
hLegend = legend(findall(gca,'Tag','Box'), {'Exp. w. adjustment','Exp. w/o adjustment'},'Orientation','horizontal','Location','NorthWest');
set(figure_t, 'Position', [100, 100, 550, 220]);
